compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /root/code/kaggle-workspace/scripts/zero_stage3_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
zero3_save_16bit_model: true
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
